# standard jekyll configuration

permalink: date
highlighter: pygments
exclude: ['Gemfile', 'Gemfile.lock']
markdown: rdiscount

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "doc"
      lang: "en_US"

